# Generated by Django 3.2 on 2022-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='id_phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
