# Generated by Django 3.2 on 2022-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calllog_id_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='id_phone',
            new_name='id_device',
        ),
    ]
