# Generated by Django 3.2 on 2022-04-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_phone_calllog_id_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='id_log',
            new_name='id_device',
        ),
    ]
